### PR TITLE
Improve app nav

### PR DESCRIPTION
**Pull request by schwalbs**
Minor design tweak to prevent the app nav logo from flowing over the nav options.

## Before
Screen Shot 2021-04-14 at 12 07 54

## After
Screen Shot 2021-04-14 at 12 07 46

### CODE REVIEW

**Review by yorker78 — APPROVED** [review]
LGTM, but best to wait on whatever active is now webmaster

Off Topic - New webmaster apparently wants to outsource the website to a design firm?

**Comment by schwalbs** [comment]
> Off Topic - New webmaster apparently wants to outsource the website to a design firm?

Eh why not, it's a pain to maintain. It's a fun side project, but obv no one's been motivated enough to clean up my sloppy code.

**Comment by yorker78** [comment]
> > Off Topic - New webmaster apparently wants to outsource the website to a design firm?
> 
> Eh why not, it's a pain to maintain. It's a fun side project, but obv no one's been motivated enough to clean up my sloppy code.

Just seems like spending money just to spend money when it's pretty simple, at least to me, to update it. Sure the code is sloppy, but it's functional and looked better than other fraternities' sites when I left.

**Review by kleinpa — CHANGES_REQUESTED** [review]
Delete .DS_Store.

**Comment by kleinpa** [comment]
> obv no one's been motivated enough to clean up my sloppy code

Hey I tried 🤷🏻

Paying for something like squarespace seems like a reasonable move if that's what they're talking about and that's 100% the active chapter's decision to make, but I do think we're best off convincing some csse active to keep this one up to date.

**Review by kleinpa — APPROVED** [review]

**Pull request merged**
