### PR TITLE
Use Jekyll

### PR DESCRIPTION
**Pull request by kleinpa**

### CODE REVIEW

**Comment by kleinpa** [comment]
Jekyll is sweet and supported naively by GitHub Pages. This change extracts the common layout into it's own file. I also committed the docker-compose file I used while working on it, it should be all you need to test it out locally.

**Comment by yorker78** [comment]
I'll look into it when I have some time this weekend if that's alright with you.

**Comment by schwalbs** [comment]
@yorker78 did you have time to look into it?

**Comment by yorker78** [comment]
> @yorker78 did you have time to look into it?

No, haven't had the chance yet. Maybe this weekend. Follow up with me in another 3.5 years if I don't get around to it then

**Comment by DavidPurdy1** [comment]
Yo so what are we thinking on this? Going to revamp the website maybe a bit. Anyone have any other suggestions? Somewhat familiar with jekyll, but if anyone has anything they think might be better, I might either go for it tomorrow or Monday. Goal is to make this website idiot proof. i.e maybe just like updating a config file quarter to quarter for brothers info. @kleinpa @yorker78 @schwalbs

**Comment by kleinpa** [comment]
I think GitHub Actions now let you publish to Pages from any static site generator so just pick whichever tool you're most familiar with, they all do basically the same stuff.

**Comment by schwalbs** [comment]
Agree with @kleinpa, but with some sauce thrown in. I recommend using something more common. I won't be able to help with anything ruby, and idk how applicable it'll be in work. Maybe look into a python solution, but really it doesn't matter.

Also please keep your PRs smaller than this, we can't reasonably give good feedback with 16 file, 3000 line changes.

**Comment by kleinpa** [comment]
For what it's worth Jekyll was a great choice in 2017. I used Hugo a few years ago and thought it was nice but I think it's already out of vogue. https://www.11ty.dev/ is all the rage these days and is built on of Node but I've never used it myself.

Whatever you pick, it'll seem like a weird choice in a couple years.

**Comment by kleinpa** [comment]
Let's continue discussion in issue #19

**Pull request closed without merging**
